### PR TITLE
Fix Chinese text tokenize issue and malformed self-closing tag parsing issue

### PR DESCRIPTION
**Pull request by wubin1989**
Hi, Josh. Thank you for this awesome library. It really saved my a lot of time.
It works very well for English news web page, but can not extract content from Chinese page, so I made some fix according to boilerpipe-1.2.1-sources.jar of Dr. Christian Kohlschütter.
Hope the fix can help other people!

### CODE REVIEW

**Comment by jlubawy** [comment]
Thank you for the PR, I appreciate it!

Is it possible for you to include an example or two of Chinese article HTML files and the text you expect? I'd like to add it to the tests that to make sure it doesn't break again in the future.

See the `testdata` directory for some examples.

**Comment by wubin1989** [comment]
I added three Chinese html files in testdata directory and the test ExampleParseDocument passed.

**Comment by jlubawy** [comment]
Thank you!

I made some minor changes and created a PR on your branch https://github.com/wubin1989/go-boilerpipe/pull/1

If you can approve that then I can merge your changes.

**Comment by jlubawy** [comment]
Actually I went ahead and just merged it here: https://github.com/jlubawy/go-boilerpipe/commit/347db382a832470ab9beeab837fad2544f97cb18

If you have any more issues let me know, and thank you again for fixing this!

**Pull request closed without merging**
